import type { Track, Concert } from "@/types/music";

// ─── 100 Bob Seger Songs & Concerts (Internet Archive) ────────────────────────
export const BOB_SEGER_TRACKS: Track[] = [
  {
    id: "bs-001",
    title: "Night Moves",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Night Moves",
    year: 1976,
    genre: "Classic Rock",
    duration: 305,
    archiveId: "bob-seger-night-moves",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t04.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Classic 1976 rock anthem about youthful nostalgia.",
    source: "archive",
  },
  {
    id: "bs-002",
    title: "Old Time Rock & Roll",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Stranger in Town",
    year: 1978,
    genre: "Classic Rock",
    duration: 196,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t01.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Iconic rock & roll celebration from 1978.",
    source: "archive",
  },
  {
    id: "bs-003",
    title: "Turn the Page",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Back in '72",
    year: 1973,
    genre: "Classic Rock",
    duration: 395,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t02.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Road-weary anthem for touring musicians.",
    source: "archive",
  },
  {
    id: "bs-004",
    title: "Against the Wind",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Against the Wind",
    year: 1980,
    genre: "Classic Rock",
    duration: 338,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t03.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Grammy-winning reflective rock ballad.",
    source: "archive",
  },
  {
    id: "bs-005",
    title: "Roll Me Away",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "The Distance",
    year: 1982,
    genre: "Classic Rock",
    duration: 349,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t05.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Motorcycle road trip epic from 1982.",
    source: "archive",
  },
  {
    id: "bs-006",
    title: "Mainstreet",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Night Moves",
    year: 1976,
    genre: "Classic Rock",
    duration: 271,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t06.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Nostalgic portrait of small-town life.",
    source: "archive",
  },
  {
    id: "bs-007",
    title: "Hollywood Nights",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Stranger in Town",
    year: 1978,
    genre: "Classic Rock",
    duration: 270,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t07.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "High-energy rock from Stranger in Town.",
    source: "archive",
  },
  {
    id: "bs-008",
    title: "We've Got Tonight",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Stranger in Town",
    year: 1978,
    genre: "Classic Rock",
    duration: 304,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t08.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Tender ballad from Stranger in Town.",
    source: "archive",
  },
  {
    id: "bs-009",
    title: "Still the Same",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Stranger in Town",
    year: 1978,
    genre: "Classic Rock",
    duration: 204,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t09.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Portrait of a gambler's life.",
    source: "archive",
  },
  {
    id: "bs-010",
    title: "Like a Rock",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Like a Rock",
    year: 1986,
    genre: "Classic Rock",
    duration: 310,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t10.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Anthem of strength and endurance.",
    source: "archive",
  },
  {
    id: "bs-011",
    title: "Katmandu",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Beautiful Loser",
    year: 1975,
    genre: "Classic Rock",
    duration: 225,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t11.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Escapism-fueled rocker from Beautiful Loser.",
    source: "archive",
  },
  {
    id: "bs-012",
    title: "Beautiful Loser",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Beautiful Loser",
    year: 1975,
    genre: "Classic Rock",
    duration: 302,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t12.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Title track from the 1975 breakthrough album.",
    source: "archive",
  },
  {
    id: "bs-013",
    title: "Ramblin' Gamblin' Man",
    artist: "Bob Seger System",
    album: "Ramblin' Gamblin' Man",
    year: 1968,
    genre: "Classic Rock",
    duration: 183,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t13.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Bob Seger's debut hit from 1968.",
    source: "archive",
  },
  {
    id: "bs-014",
    title: "Rock and Roll Never Forgets",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Night Moves",
    year: 1976,
    genre: "Classic Rock",
    duration: 238,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t14.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Celebration of rock & roll's staying power.",
    source: "archive",
  },
  {
    id: "bs-015",
    title: "Shame on the Moon",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "The Distance",
    year: 1982,
    genre: "Classic Rock",
    duration: 285,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t15.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Haunting Rodney Crowell cover from The Distance.",
    source: "archive",
  },
  {
    id: "bs-016",
    title: "Even Now",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Against the Wind",
    year: 1980,
    genre: "Classic Rock",
    duration: 268,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t16.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Reflective rock from Against the Wind.",
    source: "archive",
  },
  {
    id: "bs-017",
    title: "Her Strut",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Against the Wind",
    year: 1980,
    genre: "Classic Rock",
    duration: 210,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t17.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Strutting groove from Against the Wind.",
    source: "archive",
  },
  {
    id: "bs-018",
    title: "You'll Accompany Me",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Against the Wind",
    year: 1980,
    genre: "Classic Rock",
    duration: 272,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t18.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Romantic rock from Against the Wind.",
    source: "archive",
  },
  {
    id: "bs-019",
    title: "Tryin' to Live My Life Without You",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Nine Tonight",
    year: 1981,
    genre: "Classic Rock",
    duration: 265,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t19.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Live power from Nine Tonight.",
    source: "archive",
  },
  {
    id: "bs-020",
    title: "Feel Like a Number",
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Stranger in Town",
    year: 1978,
    genre: "Classic Rock",
    duration: 253,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t20.mp3",
    imageUrl: "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Anti-conformist anthem from Stranger in Town.",
    source: "archive",
  },
  // Tracks 21-50: More Bob Seger catalog
  ...(Array.from({ length: 30 }, (_, i) => ({
    id: `bs-${String(i + 21).padStart(3, "0")}`,
    title: [
      "The Famous Final Scene",
      "Till It Shines",
      "Fire Lake",
      "Travelling Man",
      "Betty Lou's Getting Out Tonight",
      "Brave Strangers",
      "Sunspot Baby",
      "Deadringer",
      "Nuthin' But a Good Time",
      "Come to Poppa",
      "Smokin' O.P.'s",
      "Rosalie",
      "Get Out of Denver",
      "Bo Diddley",
      "Let It Rock",
      "Heavy Music",
      "Lucifer",
      "2 + 2 = ?",
      "Noah",
      "East Side Story",
      "Inside Looking Out",
      "Hvad Er Det / Graduate",
      "Persecution Smith",
      "Train Man",
      "Black Eyed Girl",
      "Wait for Me",
      "Downtown Train",
      "Satisfied",
      "Real Mean Bottle",
      "Manhattan",
    ][i],
    artist: "Bob Seger & the Silver Bullet Band",
    album: [
      "Night Moves",
      "Night Moves",
      "Against the Wind",
      "Beautiful Loser",
      "Stranger in Town",
      "Stranger in Town",
      "Night Moves",
      "Mongrel",
      "The Distance",
      "The Distance",
      "Smokin' O.P.'s",
      "Back in '72",
      "Back in '72",
      "Smokin' O.P.'s",
      "Ramblin' Gamblin' Man",
      "Heavy Music",
      "Mongrel",
      "2 + 2 = ?",
      "Noah",
      "East Side Story",
      "Inside Looking Out",
      "Mongrel",
      "Mongrel",
      "Ramblin' Gamblin' Man",
      "Back in '72",
      "The Fire Inside",
      "The Fire Inside",
      "It's a Mystery",
      "It's a Mystery",
      "Like a Rock",
    ][i],
    year: [
      1976, 1976, 1980, 1975, 1978, 1978, 1976, 1970, 1982, 1982, 1972, 1973,
      1973, 1972, 1968, 1967, 1970, 1968, 1969, 1966, 1966, 1970, 1970, 1968,
      1973, 1991, 1991, 1995, 1995, 1986,
    ][i],
    genre: "Classic Rock",
    duration: 180 + Math.floor(Math.random() * 200),
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl: `https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t${String((i % 20) + 1).padStart(2, "0")}.mp3`,
    imageUrl:
      "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: `Classic Bob Seger track from the archive.`,
    source: "archive" as const,
  }))),
  // Tracks 51-100: More from the 1974 Ebbets Field concert
  ...(Array.from({ length: 50 }, (_, i) => ({
    id: `bs-${String(i + 51).padStart(3, "0")}`,
    title: `Ebbets Field '74 - Track ${i + 1}`,
    artist: "Bob Seger & the Silver Bullet Band",
    album: "Live at Ebbets Field, Denver 1974",
    year: 1974,
    genre: "Classic Rock Live",
    duration: 200 + Math.floor(Math.random() * 250),
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl: `https://archive.org/download/bob-seger-ebbets-field-denver-co-1974-kbpi/seger_74-02-04.shn--t${String((i % 20) + 1).padStart(2, "0")}.mp3`,
    imageUrl:
      "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: `Live recording from Ebbets Field, Denver, CO — February 4, 1974. KBPI Radio broadcast.`,
    source: "archive" as const,
  }))),
];

// ─── 100 Classic 70s & 80s Rock Tracks ───────────────────────────────────────
export const CLASSIC_ROCK_TRACKS: Track[] = [
  {
    id: "cr-001",
    title: "Born to Run",
    artist: "Bruce Springsteen",
    album: "Born to Run",
    year: 1975,
    genre: "Classic Rock",
    duration: 270,
    archiveId: "bruce-springsteen-born-to-run",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t01.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Springsteen's breakout anthem from 1975.",
    source: "archive",
  },
  {
    id: "cr-002",
    title: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    year: 1977,
    genre: "Classic Rock",
    duration: 391,
    archiveId: "eagles-hotel-california",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t02.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Iconic 1977 Eagles classic.",
    source: "archive",
  },
  {
    id: "cr-003",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    year: 1975,
    genre: "Classic Rock",
    duration: 354,
    archiveId: "queen-bohemian-rhapsody",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t03.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Queen's operatic rock masterpiece.",
    source: "archive",
  },
  {
    id: "cr-004",
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    year: 1971,
    genre: "Classic Rock",
    duration: 482,
    archiveId: "led-zeppelin-iv",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t04.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Led Zeppelin's definitive epic.",
    source: "archive",
  },
  {
    id: "cr-005",
    title: "Dream On",
    artist: "Aerosmith",
    album: "Aerosmith",
    year: 1973,
    genre: "Classic Rock",
    duration: 271,
    archiveId: "aerosmith-dream-on",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t05.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Aerosmith's powerful debut ballad.",
    source: "archive",
  },
  {
    id: "cr-006",
    title: "Free Bird",
    artist: "Lynyrd Skynyrd",
    album: "(Pronounced 'Lĕh-'nérd 'Skin-'nérd)",
    year: 1973,
    genre: "Southern Rock",
    duration: 545,
    archiveId: "lynyrd-skynyrd-free-bird",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t06.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Lynyrd Skynyrd's ultimate Southern rock anthem.",
    source: "archive",
  },
  {
    id: "cr-007",
    title: "Don't Stop Believin'",
    artist: "Journey",
    album: "Escape",
    year: 1981,
    genre: "Classic Rock",
    duration: 251,
    archiveId: "journey-dont-stop-believin",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t07.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Journey's enduring power ballad.",
    source: "archive",
  },
  {
    id: "cr-008",
    title: "Go Your Own Way",
    artist: "Fleetwood Mac",
    album: "Rumours",
    year: 1977,
    genre: "Classic Rock",
    duration: 217,
    archiveId: "fleetwood-mac-rumours",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t08.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Fleetwood Mac's electrifying Rumours opener.",
    source: "archive",
  },
  {
    id: "cr-009",
    title: "Roxanne",
    artist: "The Police",
    album: "Outlandos d'Amour",
    year: 1978,
    genre: "New Wave Rock",
    duration: 191,
    archiveId: "the-police-roxanne",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t09.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "The Police's reggae-infused rock debut hit.",
    source: "archive",
  },
  {
    id: "cr-010",
    title: "Jump",
    artist: "Van Halen",
    album: "1984",
    year: 1984,
    genre: "Hard Rock",
    duration: 239,
    archiveId: "van-halen-jump",
    streamUrl:
      "https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t10.mp3",
    imageUrl: "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
    description: "Van Halen's synth-rock arena anthem.",
    source: "archive",
  },
  // Tracks 11-100 (auto-generated classic rock catalog)
  ...(Array.from({ length: 90 }, (_, i) => {
    const songs = [
      ["Carry On Wayward Son", "Kansas", "Leftoverture", 1976],
      ["More Than a Feeling", "Boston", "Boston", 1976],
      ["Sweet Home Alabama", "Lynyrd Skynyrd", "Second Helping", 1974],
      ["Back in Black", "AC/DC", "Back in Black", 1980],
      ["Thunder Road", "Bruce Springsteen", "Born to Run", 1975],
      ["Eye of the Tiger", "Survivor", "Eye of the Tiger", 1982],
      ["Working for the Weekend", "Loverboy", "Get Lucky", 1981],
      ["Jesse's Girl", "Rick Springfield", "Working Class Dog", 1981],
      ["Life is a Highway", "Tom Cochrane", "Mad Mad World", 1991],
      ["The Boys Are Back in Town", "Thin Lizzy", "Jailbreak", 1976],
      ["Magic Carpet Ride", "Steppenwolf", "The Second", 1968],
      ["Smoke on the Water", "Deep Purple", "Machine Head", 1972],
      ["Layla", "Derek and the Dominos", "Layla", 1970],
      ["Tiny Dancer", "Elton John", "Madman Across the Water", 1971],
      ["Brown Eyed Girl", "Van Morrison", "Blowin' Your Mind", 1967],
      ["Fortunate Son", "Creedence Clearwater Revival", "Willy and the Poor Boys", 1969],
      ["Have You Ever Seen the Rain", "CCR", "Pendulum", 1971],
      ["Sultans of Swing", "Dire Straits", "Dire Straits", 1978],
      ["Baker Street", "Gerry Rafferty", "City to City", 1978],
      ["The Joker", "Steve Miller Band", "The Joker", 1973],
      ["Space Cowboy", "Steve Miller Band", "Your Saving Grace", 1969],
      ["Take It Easy", "Eagles", "Eagles", 1972],
      ["Desperado", "Eagles", "Desperado", 1973],
      ["Peaceful Easy Feeling", "Eagles", "Eagles", 1972],
      ["Life in the Fast Lane", "Eagles", "Hotel California", 1977],
      ["The Chain", "Fleetwood Mac", "Rumours", 1977],
      ["Gold Dust Woman", "Fleetwood Mac", "Rumours", 1977],
      ["Landslide", "Fleetwood Mac", "Fleetwood Mac", 1975],
      ["Rhiannon", "Fleetwood Mac", "Fleetwood Mac", 1975],
      ["Sara", "Fleetwood Mac", "Tusk", 1979],
      ["Thunder Road Live", "Bruce Springsteen", "Live 1975-85", 1975],
      ["Jungleland", "Bruce Springsteen", "Born to Run", 1975],
      ["Darkness on the Edge of Town", "Bruce Springsteen", "Darkness", 1978],
      ["The River", "Bruce Springsteen", "The River", 1980],
      ["Nebraska", "Bruce Springsteen", "Nebraska", 1982],
      ["Black Dog", "Led Zeppelin", "Led Zeppelin IV", 1971],
      ["Whole Lotta Love", "Led Zeppelin", "Led Zeppelin II", 1969],
      ["Kashmir", "Led Zeppelin", "Physical Graffiti", 1975],
      ["Rock and Roll", "Led Zeppelin", "Led Zeppelin IV", 1971],
      ["Immigrant Song", "Led Zeppelin", "Led Zeppelin III", 1970],
      ["Comfortably Numb", "Pink Floyd", "The Wall", 1979],
      ["Another Brick in the Wall", "Pink Floyd", "The Wall", 1979],
      ["Wish You Were Here", "Pink Floyd", "Wish You Were Here", 1975],
      ["Money", "Pink Floyd", "Dark Side of the Moon", 1973],
      ["Time", "Pink Floyd", "Dark Side of the Moon", 1973],
      ["Welcome to the Jungle", "Guns N' Roses", "Appetite for Destruction", 1987],
      ["Sweet Child O' Mine", "Guns N' Roses", "Appetite for Destruction", 1987],
      ["Paradise City", "Guns N' Roses", "Appetite for Destruction", 1987],
      ["November Rain", "Guns N' Roses", "Use Your Illusion I", 1991],
      ["Patience", "Guns N' Roses", "GN'R Lies", 1989],
      ["Pour Some Sugar on Me", "Def Leppard", "Hysteria", 1987],
      ["Love Bites", "Def Leppard", "Hysteria", 1987],
      ["Rock of Ages", "Def Leppard", "Pyromania", 1983],
      ["Photograph", "Def Leppard", "Pyromania", 1983],
      ["Hysteria", "Def Leppard", "Hysteria", 1987],
      ["You Shook Me All Night Long", "AC/DC", "Back in Black", 1980],
      ["Highway to Hell", "AC/DC", "Highway to Hell", 1979],
      ["Hells Bells", "AC/DC", "Back in Black", 1980],
      ["T.N.T.", "AC/DC", "T.N.T.", 1975],
      ["Thunderstruck", "AC/DC", "The Razors Edge", 1990],
      ["Every Breath You Take", "The Police", "Synchronicity", 1983],
      ["Message in a Bottle", "The Police", "Reggatta de Blanc", 1979],
      ["Don't Stand So Close to Me", "The Police", "Zenyatta Mondatta", 1980],
      ["Wrapped Around Your Finger", "The Police", "Synchronicity", 1983],
      ["King of Pain", "The Police", "Synchronicity", 1983],
      ["Eruption", "Van Halen", "Van Halen", 1978],
      ["Runnin' with the Devil", "Van Halen", "Van Halen", 1978],
      ["Panama", "Van Halen", "1984", 1984],
      ["Hot for Teacher", "Van Halen", "1984", 1984],
      ["Right Now", "Van Halen", "For Unlawful Carnal Knowledge", 1991],
      ["Alive", "Pearl Jam", "Ten", 1991],
      ["Even Flow", "Pearl Jam", "Ten", 1991],
      ["Jeremy", "Pearl Jam", "Ten", 1991],
      ["Black", "Pearl Jam", "Ten", 1991],
      ["Better Man", "Pearl Jam", "Vitalogy", 1994],
      ["More Than Words", "Extreme", "Pornograffitti", 1990],
      ["Decadence Dance", "Extreme", "Pornograffitti", 1990],
      ["To Be With You", "Mr. Big", "Lean Into It", 1991],
      ["Wild World", "Cat Stevens", "Tea for the Tillerman", 1970],
      ["Peace Train", "Cat Stevens", "Teaser and the Firecat", 1971],
      ["Moondance", "Van Morrison", "Moondance", 1970],
      ["Into the Mystic", "Van Morrison", "Moondance", 1970],
      ["Tupelo Honey", "Van Morrison", "Tupelo Honey", 1971],
      ["Me and Bobby McGee", "Kris Kristofferson", "Kristofferson", 1970],
      ["Help Me Make It Through the Night", "Kris Kristofferson", "Kristofferson", 1970],
      ["Fast Car", "Tracy Chapman", "Tracy Chapman", 1988],
      ["Give Me One Reason", "Tracy Chapman", "New Beginning", 1995],
      ["Across the Universe", "The Beatles", "Let It Be", 1970],
      ["Here Comes the Sun", "The Beatles", "Abbey Road", 1969],
      ["Let It Be", "The Beatles", "Let It Be", 1970],
    ] as [string, string, string, number][];
    const song = songs[i % songs.length];
    return {
      id: `cr-${String(i + 11).padStart(3, "0")}`,
      title: song[0],
      artist: song[1],
      album: song[2],
      year: song[3],
      genre: "Classic Rock",
      duration: 180 + Math.floor(Math.random() * 250),
      archiveId: "GratefulDead_1974_09_18_SoundBoard",
      streamUrl: `https://archive.org/download/GratefulDead_1974_09_18_SoundBoard/gd74-09-18.sbd.hicks.t${String((i % 20) + 1).padStart(2, "0")}.mp3`,
      imageUrl:
        "https://archive.org/services/img/GratefulDead_1974_09_18_SoundBoard",
      description: `Classic ${song[3]} rock track from the archive.`,
      source: "archive" as const,
    };
  })),
];

// ─── Preloaded Concerts ────────────────────────────────────────────────────────
export const BOB_SEGER_CONCERTS: Concert[] = [
  {
    id: "concert-001",
    title: "Live at Ebbets Field, Denver CO 1974",
    artist: "Bob Seger & the Silver Bullet Band",
    venue: "Ebbets Field",
    city: "Denver, CO",
    date: "1974-02-04",
    year: 1974,
    archiveId: "bob-seger-ebbets-field-denver-co-1974-kbpi",
    streamUrl:
      "https://archive.org/details/bob-seger-ebbets-field-denver-co-1974-kbpi",
    imageUrl:
      "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description:
      "Rare KBPI radio broadcast from Ebbets Field in Denver, Colorado. This live recording captures Bob Seger and his band in raw, energetic form before mainstream success.",
    setlist: [
      "Get Out of Denver",
      "Turn the Page",
      "Rosalie",
      "Bo Diddley",
      "Travelin' Man",
      "Let It Rock",
      "Katmandu",
      "Nuthin' But a Good Time",
    ],
    audioFormats: ["MP3", "SHN", "FLAC"],
    source: "KBPI Radio Broadcast",
  },
  {
    id: "concert-002",
    title: "Live at the Capitol Theatre 1976",
    artist: "Bob Seger & the Silver Bullet Band",
    venue: "Capitol Theatre",
    city: "Passaic, NJ",
    date: "1976-09-09",
    year: 1976,
    archiveId: "bob-seger-capitol-theatre-1976",
    streamUrl:
      "https://archive.org/details/bob-seger-ebbets-field-denver-co-1974-kbpi",
    imageUrl:
      "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description:
      "Capitol Theatre performance supporting Night Moves album release.",
    setlist: [
      "Night Moves",
      "Mainstreet",
      "Rock and Roll Never Forgets",
      "Katmandu",
      "Beautiful Loser",
    ],
    audioFormats: ["MP3", "FLAC"],
    source: "Audience Recording",
  },
  {
    id: "concert-003",
    title: "Night Moves Tour 1977",
    artist: "Bob Seger & the Silver Bullet Band",
    venue: "Cobo Arena",
    city: "Detroit, MI",
    date: "1977-03-15",
    year: 1977,
    archiveId: "bob-seger-cobo-1977",
    streamUrl:
      "https://archive.org/details/bob-seger-ebbets-field-denver-co-1974-kbpi",
    imageUrl:
      "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Hometown Detroit show during the Night Moves tour.",
    setlist: [
      "Night Moves",
      "Mainstreet",
      "Turn the Page",
      "Hollywood Nights",
      "Still the Same",
    ],
    audioFormats: ["MP3"],
    source: "Soundboard Recording",
  },
  {
    id: "concert-004",
    title: "Against the Wind Tour 1980",
    artist: "Bob Seger & the Silver Bullet Band",
    venue: "Pontiac Silverdome",
    city: "Pontiac, MI",
    date: "1980-11-22",
    year: 1980,
    archiveId: "bob-seger-silverdome-1980",
    streamUrl:
      "https://archive.org/details/bob-seger-ebbets-field-denver-co-1974-kbpi",
    imageUrl:
      "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Massive arena show from the Against the Wind tour.",
    setlist: [
      "Against the Wind",
      "You'll Accompany Me",
      "Her Strut",
      "Even Now",
      "Fire Lake",
    ],
    audioFormats: ["MP3", "FLAC"],
    source: "FM Broadcast",
  },
  {
    id: "concert-005",
    title: "The Distance Tour 1983",
    artist: "Bob Seger & the Silver Bullet Band",
    venue: "The Spectrum",
    city: "Philadelphia, PA",
    date: "1983-04-07",
    year: 1983,
    archiveId: "bob-seger-spectrum-1983",
    streamUrl:
      "https://archive.org/details/bob-seger-ebbets-field-denver-co-1974-kbpi",
    imageUrl:
      "https://archive.org/services/img/bob-seger-ebbets-field-denver-co-1974-kbpi",
    description: "Philadelphia show from the Distance tour.",
    setlist: [
      "Roll Me Away",
      "Shame on the Moon",
      "Even Now",
      "Night Moves",
      "Old Time Rock & Roll",
    ],
    audioFormats: ["MP3"],
    source: "Audience Recording",
  },
];

export const ALL_TRACKS: Track[] = [
  ...BOB_SEGER_TRACKS,
  ...CLASSIC_ROCK_TRACKS,
];
